name: CI

on:
  push:
    branches:
    - main
  pull_request:

env:
  # The NAME makes it easier to copy/paste snippets from other CI configs
  NAME: yapall

jobs:
  doc:
    runs-on: ubuntu-latest
    permissions:
      # Cancel workflow
      actions: write
      # Upload docs
      contents: write
    steps:
    - name: Cancel previous run
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v3

    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: '0.4.33'

    - name: Build docs
      run: |
        cd doc
        mdbook build

    - name: Push docs
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: doc/book

    - name: Package docs
      shell: bash
      run: |
        tar -cvf doc.tar.gz doc/book/*

    # TODO
    # - name: Upload docs
    #   uses: actions/upload-artifact@v3
    #   if: github.repository == 'GaloisInc/${{ env.NAME }}'
    #   with:
    #     name: "${{ env.NAME }}-docs"
    #     path: "*.tar.gz"
    #     if-no-files-found: error
